pipeline{
  agent any
  environment{
    DOCKER_USER="shriram2105"
  }
  stages{
    stage('Checkout'){
      steps{
        checkout scm
      }
    }
    stage("Building Frontend"){
      steps{
        dir('app/NoteBook_FrontEnd'){
          sh "docker build -t ${DOCKER_USER}/notebook-frontend:latest ."
        }
      }
    }
    stage("Building"){
      steps{
        dir("app/NoteBook_BackEnd"){
          sh "docker build -t ${DOCKER_USER}/notebook-backend:latest ."
        }
      }
    }
    stage("Pushing images to Hub"){
      steps{
        withCredentials([usernamePassword(
          credentialsId: "docker-userPass",
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]){
          sh '''
            echo "$PASS" | docker login -u "$USER" --password-stdin
            docker push ${DOCKER_USER}/notebook-frontend:latest
            docker push ${DOCKER_USER}/notebook-backend:latest
          '''
        }
      }
    }
  }
  post{
    always {
        echo"build finished with status: ${currentBuild.currentResult}"
        sh "docker logout || true"
    }
    success{
      echo "Build was successful. Docker image pushed to the registry."
    }
    failure{
       echo "Build failed. Please check the logs for more details."
    }
  }
}