pipeline{
  agent any
  stages{
    stage('Checkout'){
      steps{
        checkout scm
      }
    }
    stage('Build Images'){
      steps{
        sh """
          cd /var/jenkins_home/workspace/Notebook-App_feature/app/NoteBook_FrontEnd

          echo " Building Frontend"
          docker build -t shriram2105/notebook-frontend:latest .

          echo "Building Building Backend"
          docker build -t shriram2105/notebook-backend:latest .
        """
      }
    }
    stage("Pushing images to Hub"){
      steps{
        sh """
          docker login -u shriram2105

          docker push shriram2105/notebook-frontend:latest

          docker push shriram2105/notebook-backend:latest
          
        """
      }
    }
  }
  post{
    always {
        echo"build finished with status: ${currentBuild.currentResult}"
    }
    success{
      echo "Build was successful. Docker image pushed to the registry."
    }
    failure{
       echo "Build failed. Please check the logs for more details."
    }
  }
}